### ISSUE TITLE
Support multiple output args in computeFunctions

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#140]
Currently, `computeFunctions` only return one argument (an array). Make it possible for cFs to return a tuple of *serializable* output objects.

**Comment by tensionhead** [comment]
As suggested by @pantaray we could maybe use the `noCompute` dry-runs to validate the additional data inherent (but out of reach atm, hence we have to blindly trust everything inside a cF goes as planned) in the computations, e.g. the `freq` axis for spectral methods.

**Comment by tensionhead** [comment]
The current idea is to piggy-back along the hdf5 file(s) every worker is working on. Meaning we add (transient, not respected by `spy.save` for example) additional fields to each (virtual) hdf5 container, holding the desired outputs.

**Comment by dfsp-spirit** [comment]
Ideas from todays meeting:
* We will use [hdf5 attributes](https://docs.h5py.org/en/stable/high/attr.html) to store a single, additional return value of a user-supplied cF.
* The 2nd return value must be a shallow dictionary, with keys holding numpy ndarrays
* The ndarrays are size-limited, see the hdf5 attribute docs above. Returning *a lot* of data (e.g., in range of the number of input values) would require creating additional *datasets* in the hdf5. We could allow this, by indicating in some way that an attribute is stored in a separate dataset instead of in the value of the dictionary key (e.g., by having the keys as tuples of type `(str, bool)` with meaning `(<freeform_extra_return_value_name>, <is_in_extra_dataset>)`.
