### ISSUE TITLE
FT Importer

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#204]
We need the basic functionality to import native `.mat` FT data files into Syncopy. As a first step, try to write an importer which takes FT time-series data and returns AnalogData objects

**Comment by joschaschmiedt** [comment]
Something that may require some attention is compression. MATLAB's [`save`](https://de.mathworks.com/help/matlab/ref/save.html) compresses the v7.3 files by default, which can be disabled since MATLAB 2017a with the `'-nocompression'` flag. I don't know how this manifests itself in the HDF5 file, but should probably be checked once.

**Comment by tensionhead** [comment]
Got it working for both MAT-Files v7 and v7.3, tests are still missing
