### ISSUE TITLE
dpss window: check units of bandwidth parameter

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#58]
The bandwidth parameter  of the dpss windows (`NW`) in `mtmfft` is not yet well defined. This should be clarified.

**Comment by tensionhead** [comment]
According to scipy's documentation, it's defined as
```
'''
NW : float

    Standardized half bandwidth corresponding to 2*NW = BW/f0 = BW*M*dt where dt is taken as 1.
'''
```
which I agree isn't really clear. It's definitely no 'smoothing frequency in Hz' as it's in the doc right now, as `tapsmofrq` gets mapped directly onto `NW`. The actual frequency smoothing is controlled by both `Kmax` and `NW` parameters. WE'll probably have to dig deeper to have the same `tapsmofrq` as in FieldTrip.

**Comment by tensionhead** [comment]
Ok I think I got it, according to the paper: "The Effective Bandwidth of a Multitaper Spectral Estimator, A. T. Walden, E. J. McCoy and D. B. Percival" the number of tapers, the effective bandwidth and the lenght of the signal are of course all connected. From their paper: 
![Screenshot from 2021-11-11 16:24:40](https://user-images.githubusercontent.com/10595420/141324132-8af41e3c-f57e-4cf4-adfe-66fd65549487.png)
 Where NW is the product of signal length `N` and half-bandwidth `W`, we see that to actual reach a desired bandwidth `2W` we have to max out the tapers, but not go over the limit `Kmax = 2NW-1` (due to side-lobe minimisation, which otherwise fails and regions far away from actual spectral peaks get amplified) . This also means there is a minimal frequency smoothing bandwidth, given by `2W > 2fs / N`. So I propose to implement that in the respective frontends, that means deleting the `nTaper` option as this doesn't make much sense actually!

**Comment by pantaray** [comment]
Thanks for going down the rabbit hole with this one, @tensionhead ! I agree, that manually setting `nTaper` has great potential to sabotage one's spectral analysis. However, I think we should still provide the possibility to enforce a specific taper count (maybe accompanied by a stern warning message in the terminal). So I'd vote for Option #2: keep `nTaper` and `tapsmofrq` but make them mutually exclusive options. Would you be okay with that?

**Comment by tensionhead** [comment]
Ok I followed through with this as suggested by @pantaray One downside of the new now correct DPSS settings is, that the self-proclaimed *sane* automatic setting ("3/4 Octave") for `tapsmofrq` within the specest frontend gives rather large values, like 25Hz. The optimal number of tapers in this case can easily go up to 100 for long (~4000 samples) signals. However this is still correct as shown in this little example plot here (4000 samples, tapsmofrq = 15Hz):
![Screenshot from 2021-11-12 16:12:53](https://user-images.githubusercontent.com/10595420/141491045-8f0ac3f2-c631-4fae-a099-1ac52a7d1f9f.png)
The optimal number of Tapers is 60, and only with this the full (rectangular) desired frequency smoothing bandwidth is realized. Manually setting it to half the correct number (30), rather strongly distorts the spectral estimation. 
Technically this question is resolved now, as users can input `tapsmofrq` in Hz and the rest is taken care off, with the possibility to still use a different number of tapers if desired. So closing this with c8ebf79
